version: '3.8'

services:
  # Database Services
  postgres:
    image: postgres:15-alpine
    container_name: modex-postgres
    environment:
      POSTGRES_DB: modex
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/configs/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - modex-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: modex-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - modex-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # API Gateway
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    container_name: modex-api-gateway
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-jwt-secret-key-here
      CORS_ORIGIN: "*"
      # Service URLs
      COURSE_SERVICE_URL: http://course-management:3002
      ENROLLMENT_SERVICE_URL: http://enrollment:3003
      ASSESSMENT_SERVICE_URL: http://assessment:3004
      PAYMENT_SERVICE_URL: http://payment:3005
      ANALYTICS_SERVICE_URL: http://analytics:3006
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - modex-network
    restart: unless-stopped

  # Course Management Service
  course-management:
    build:
      context: ./services/course-management
      dockerfile: Dockerfile
    container_name: modex-course-management
    ports:
      - "3002:3002"
    environment:
      GIN_MODE: release
      PORT: 3002
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/modex?sslmode=disable
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-jwt-secret-key-here
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - modex-network
    restart: unless-stopped

  # Enrollment Service
  enrollment:
    build:
      context: ./services/enrollment
      dockerfile: Dockerfile
    container_name: modex-enrollment
    ports:
      - "3003:3003"
    environment:
      NODE_ENV: production
      PORT: 3003
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/modex
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-jwt-secret-key-here
      COURSE_SERVICE_URL: http://course-management:3002
      ANALYTICS_SERVICE_URL: http://analytics:3006
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - modex-network
    restart: unless-stopped

  # Assessment Service
  assessment:
    build:
      context: ./services/assessment
      dockerfile: Dockerfile
    container_name: modex-assessment
    ports:
      - "3004:3004"
    environment:
      GIN_MODE: release
      PORT: 3004
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/modex?sslmode=disable
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-jwt-secret-key-here
      COURSE_SERVICE_URL: http://course-management:3002
      ANALYTICS_SERVICE_URL: http://analytics:3006
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - modex-network
    restart: unless-stopped

  # Payment Service
  payment:
    build:
      context: ./services/payment
      dockerfile: Dockerfile
    container_name: modex-payment
    ports:
      - "3005:3005"
    environment:
      NODE_ENV: production
      PORT: 3005
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/modex
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-jwt-secret-key-here
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      ANALYTICS_SERVICE_URL: http://analytics:3006
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - modex-network
    restart: unless-stopped

  # Analytics Service
  analytics:
    build:
      context: ./services/analytics
      dockerfile: Dockerfile
    container_name: modex-analytics
    ports:
      - "3006:3006"
    environment:
      NODE_ENV: production
      PORT: 3006
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/modex
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-jwt-secret-key-here
      BATCH_SIZE: 100
      FLUSH_INTERVAL: 5000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - modex-network
    restart: unless-stopped

  # Audit & Compliance Service
  audit:
    build:
      context: ./services/audit
      dockerfile: Dockerfile
    container_name: modex-audit
    ports:
      - "3007:3007"
    environment:
      NODE_ENV: production
      PORT: 3007
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/modex
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-jwt-secret-key-here
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - modex-network
    restart: unless-stopped

  # Search Service
  search:
    build:
      context: ./services/search
      dockerfile: Dockerfile
    container_name: modex-search
    ports:
      - "3008:3008"
    environment:
      NODE_ENV: production
      PORT: 3008
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/modex
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-jwt-secret-key-here
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - modex-network
    restart: unless-stopped

  # Event Bus Service
  event-bus:
    build:
      context: ./services/event-bus
      dockerfile: Dockerfile
    container_name: modex-event-bus
    ports:
      - "3009:3009"
    environment:
      NODE_ENV: production
      PORT: 3009
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/modex
      REDIS_URL: redis://redis:6379
      KAFKA_BROKERS: kafka:9092
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - modex-network
    restart: unless-stopped

  # Elasticsearch for Search Service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: modex-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - modex-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Kafka for Event Bus
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: modex-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - modex-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: modex-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    networks:
      - modex-network
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend - Next.js Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: modex-frontend
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    depends_on:
      - api-gateway
    networks:
      - modex-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: modex-nginx
    ports:
      - "80:80"
    volumes:
      - ./infrastructure/configs/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - api-gateway
    networks:
      - modex-network

networks:
  modex-network:
    driver: bridge
    name: modex-network

volumes:
  postgres_data:
    name: modex-postgres-data
  redis_data:
    name: modex-redis-data
  elasticsearch_data:
    name: modex-elasticsearch-data