apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  username: {{ .Values.postgresql.external.username | quote }}
  password: "{{ `{{POSTGRES_PASSWORD}}` }}" # Replaced by CI/CD
  connection-string: "postgresql://{{ .Values.postgresql.external.username }}:{{ `{{POSTGRES_PASSWORD}}` }}@{{ .Values.postgresql.external.host }}:{{ .Values.postgresql.external.port }}/{{ .Values.postgresql.external.database }}?sslmode=require"

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  password: "{{ `{{REDIS_PASSWORD}}` }}" # Replaced by CI/CD
  connection-string: "redis://default:{{ `{{REDIS_PASSWORD}}` }}@{{ .Values.redis.external.host }}:{{ .Values.redis.external.port }}/0"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  JWT_SECRET: "{{ `{{JWT_SECRET}}` }}" # Replaced by CI/CD
  STRIPE_SECRET_KEY: "{{ `{{STRIPE_SECRET_KEY}}` }}" # Replaced by CI/CD
  STRIPE_WEBHOOK_SECRET: "{{ `{{STRIPE_WEBHOOK_SECRET}}` }}" # Replaced by CI/CD
