{{- if .Values.monitoring.serviceMonitor.enabled }}
{{- range $name, $service := .Values.services }}
{{- if $service.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $name }}-service-monitor
  namespace: {{ $.Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
  endpoints:
  - port: http
    interval: {{ $.Values.monitoring.serviceMonitor.interval }}
    path: /metrics
    scheme: http
{{- end }}
{{- end }}
{{- end }}
